# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false
